_default_routes:
    resource: routing/default.yml

EventBundle_event:
    resource: "@EventBundle/Resources/config/routing/event.yml"
    prefix:   /event


event_report_updated_events:
    pattern:  /events/report/recentlyUpdated.csv
    defaults: { _controller: EventBundle:Report:updatedEvents, _format: csv }

