services:
    Event.reporting.event_report_manager:
        class: Event\EventBundle\Reporting\EventReportManager
        arguments:
            # pass the string "foo" as the first constructor argument
            - "@doctrine.orm.entity_manager"
        calls:
            - [ setLogger, ["@logger"] ]
    event.twig.event_extension:
        class:  Event\EventBundle\Twig\EventExtension
        arguments:  []
        tags:
            - { name: twig.extension }
        public: false